### ISSUE TITLE
Unknown CMake command "add_compile_definitions".

### ISSUE THREAD

**Issue by chendaichao** [MaxXSoft/MiniVM#1]
Seems that the requirements about CMake version given by `README.md`, "3.5 or later", is not enough?  I still encounter an error messsage

> Unknown CMake command "add_compile_definitions".

using my CMake with version 3.10, but it works well when upgraded to version 3.16.

**Comment by MaxXSoft** [comment]
Thanks for pointing this out!

I checked the official document, the command `add_compile_definitions` has been supported since CMake 3.12.

Fixed this issue by changing minimum required CMake version to 3.13.
