### ISSUE TITLE
External functions do not change a0~a7

### ISSUE THREAD

**Issue by semiwaker** [MaxXSoft/MiniVM#3]
External functions like putint() do not change a0~a7 in Tigger, which cause the result of the simulation of Tigger may be different from the result of RiscV.

**Comment by MaxXSoft** [comment]
Thanks for pointing this out!

A few days ago we have noticed this difference in behavior between MiniVM and GCC-compiled SysY library code, so we decided to fix this issue in the next minor release.

BTW, the behavior of the Tigger library function in MiniVM is also correct at the moment, but it doesn't help much for debugging.
